### ISSUE TITLE
issue installing requirements

### ISSUE THREAD

**Issue by Seraphina5079** [nerdyjoe314/divinationscarabs#4]
please add a requirements.txt or instructions to setup the program as i've been having issues getting scip to work

**Comment by nerdyjoe314** [comment]
There is now a readme.md. SCIP isn't included in pip, as far as I'm aware, and I'm not using any non-standard python packages. The imports are:
import json
import subprocess
import os
import time

Feel free to make a new issue if this doesn't resolve things.
